export const terms = {
    defaultPurposeDesc6: 'לארח חברה לספר ולהקשיב',
    showActivities: 'הצג פעילויות',
    opens: 'פתוחות',
    closes: 'סגורות',
    inProgress: 'בתהליך',
    endSuccess: 'הסתיימו בהצלחה',
    problems: 'בעיות',
    invalidBranch: 'סניף אינו תקין',
    appVersion: '2021.11.02.0',
    defaultVolunteers: 'מתנדבים ברירת מחדל',
    appDesc: 'אפליקציה לניהול מפגשי התנדבות',
    addVolunteer: 'הוספת מתנדב',
    requiredField: 'שדה חובה',
    addTenant: 'הוספת דייר',
    addActivity: 'הוספת פעילות',
    cancelActivity: 'בטל פעילות',
    sameDateAndTimes: 'לו"ז חופף',
    close: 'סגור',
    saveAndClose: 'שמור וסגור',
    commentAndSummary: 'הערות וסיכום פעילות',
    purpose: 'מטרה',
    passwordReset: 'סיסמא אופסה',
    resetPassword: 'איפוס סיסמא',
    activityDetails: 'פרטי פעילות',
    activity: 'פעילות',
    defaultTenant: 'דייר ברירת מחדל',
    entityType: 'סוג ישות',
    entityId: 'מזהה ישות',
    desc: 'תיאור',
    remark: 'הערות',
    name: 'שם',
    type: 'סוג',
    title: 'כותרת ראשית',
    tenant: 'דייר',
    branch: 'סניף',
    subTitle: 'כותרת משנית',
    volunteerApp: 'פעילות התנדבותית',
    currentStatus: 'סטטוס נוכחי',
    currentState: 'מצב נוכחי',
    activities: 'פעילויות',
    tenants: 'דיירים',
    fromHour: 'משעה',
    toHour: 'עד שעה',
    date: 'תאריך',
    volunteers: 'מתנדבים',
    email: 'דוא"ל',
    photo: 'תמונה',
    address: 'כתובת',
    photos: 'תמונות',
    data: 'מידע',
    birthday: 'תאריך לידה',
    status: 'סטטוס',
    mobile: "סלולרי",
    username: "שם משתמש",
    signIn: "כניסה",
    confirmPassword: "אימות סיסמא",
    signUp: "הירשמות",
    doesNotMatchPassword: "סיסמאות אינן תואמות",
    password: 'סיסמא',
    updateInfo: "עדכון פרטים",
    changePassword: "שינוי סיסמה",
    hello: "שלום",
    invalidOperation: "פעולה אינה חוקית",
    admin: 'אדמין',
    board: 'הנהלה',
    manager: 'מנהל סניף',
    volunteer: 'מתנדב',
    yes: 'כן',
    no: 'לא',
    ok: 'אישור',
    areYouSureYouWouldLikeToDelete: "האם למחוק את",
    cancel: 'ביטול',
    home: 'ברוכים הבאים',
    userAccounts: 'משתמשים',
    myActivities: 'הפעילויות שלי',
    personalInfo: 'פרטים אישיים',
    invalidSignIn: "פרטי כניסה שגויים",
    signOut: 'התנתקות'
}
declare module 'remult' {
    export interface UserInfo {
        bid: string;
    }
}
