export const terms = {
    save:'שמור',
    age: 'גיל',  
    continue: 'המשך',
    openPhotosAlbum : 'פתח אלבום תמונות',
    linkClicked:'לינק נלחץ', 
    voulnteerNewAssign:'נקבעה לך פעילות עם הדייר !name! בתאריך !date! משעה !from! עד שעה !to! בכתובת !address!',
    referrer: 'גורם מפנה', 
    volunteerNoActivities: 'תודה לך! כרגע אין לך פעילויות פתוחות',
    removeImage: 'הסרת תמונה',
    noPhotosOfYoursTogether:'לא הועלו תמונות שלכם יחד',
    created: 'נוצר', 
    createdBy: 'נוצר ע"י',
    modified: 'עודכן',
    modifiedBy: 'עודכן ע"י',
    uploadPhoto :'העלאת תמונה',
    unpoladYoursPhotosTogether:'העלו תמונות שלכם יחד',
    yoursDetailsSuccesfulySaved: 'פרטים עודכנו בהצלחה',
    langs:'שפות',
    mustSetBidForThisAction: 'חובה לבחור סניף לפני ביצוע שיבוץ',
    selected: 'נבחרו',
    deleteVolunteer: 'מחיקת מתנדב',
    deleteTenant:'מחיקת דייר',
    activitiesByWeekDay: 'פעילויות לפי ימי השבוע',
    activitiesByPurpose: 'פעילויות לפי מטרות',
    activitiesByStatuses: 'פעילויות לפי סטטוסים',
    activitiesByDayPeriods: 'פעילויות לפי זמני היום',
    activitiesByReferrer: 'פעילויות לפי גורם מפנה',
    refresh: 'רענן',
    print:'הדפס',
    addActivityToCurrentTenant:'הוסף פעילות לדייר זה',
    shouldAddActivity: 'האם להוסיף ל!t.name! פעילות חדשה?',
    shouldOpenTheActivity: 'לפתוח את הפעילות שהקמת כרגע?',
    serachForTenantNameHere: 'חיפוש לפי שם דייר..',
    serachForVolunteerHere: 'חיפוש לפי שם מתנדב..',
    selectDate: 'בחירת תאריך',
    defaultPurposeDesc6: 'לארח חברה לספר ולהקשיב',
    showActivities: 'הצג פעילויות',
    opens: 'פתוחות', 
    closes: 'סגורות',
    inProgress: 'בתהליך',
    endSuccess: 'הסתיימו בהצלחה',
    problems: 'בעיות',
    invalidBranch: 'סניף אינו תקין',
    appVersion: '2021.11.10.0',
    defaultVolunteers: 'מתנדבים ברירת מחדל',
    appDesc: 'אפליקציה לניהול מפגשי התנדבות',
    addVolunteer: 'הוספת מתנדב',
    requiredField: 'שדה חובה',
    addTenant: 'הוספת דייר',
    addActivity: 'הוספת פעילות',
    cancelActivity: 'בטל פעילות',
    sameDateAndTimes: 'לו"ז חופף',
    close: 'סגור',
    saveAndClose: 'שמור וסגור',
    commentAndSummary: 'הערות וסיכום פעילות',
    purpose: 'מטרה',
    passwordReset: 'סיסמא אופסה',
    resetPassword: 'איפוס סיסמא',
    tenantDetails: 'פרטי דייר',
    delete:'מחק',
    volunteerDetails: 'פרטי מתנדב',
    activityDetails: 'פרטי פעילות',
    activity: 'פעילות', 
    defaultTenant: 'דייר ברירת מחדל',
    entityType: 'סוג ישות',
    entityId: 'מזהה ישות',
    desc: 'תיאור',
    remark: 'הערות',
    name: 'שם',
    type: 'סוג',
    title: 'כותרת ראשית',
    tenant: 'דייר',
    branch: 'סניף',
    subTitle: 'כותרת משנית',
    volunteerApp: 'פעילות התנדבותית',
    currentStatus: 'סטטוס נוכחי',
    currentState: 'מצב נוכחי',
    activities: 'פעילויות',
    tenants: 'דיירים',
    fromHour: 'משעה',
    toHour: 'עד שעה',
    date: 'תאריך',
    reports: 'דוחות',
    dailyActivityReport: 'דוח פעילות יומי',
    volunteers: 'מתנדבים',
    email: 'דוא"ל',
    photo: 'תמונה',
    active: 'פעיל',
    address: 'כתובת',
    photos: 'תמונות',
    data: 'מידע',
    birthday: 'תאריך לידה',
    status: 'סטטוס',
    mobile: "סלולרי",
    username: "שם משתמש",
    signIn: "כניסה",
    confirmPassword: "אימות סיסמא",
    signUp: "הירשמות",
    doesNotMatchPassword: "סיסמאות אינן תואמות",
    password: 'סיסמא',
    updateInfo: "עדכון פרטים",
    changePassword: "שינוי סיסמה",
    hello: "שלום",
    invalidOperation: "פעולה אינה חוקית",
    admin: 'אדמין',
    board: 'הנהלה',
    manager: 'מנהל סניף',
    volunteer: 'מתנדב',
    yes: 'כן',
    no: 'לא',
    ok: 'אישור',
    areYouSureYouWouldLikeToDelete: "האם למחוק את ה",
    cancel: 'ביטול',
    home: 'ברוכים הבאים',
    userAccounts: 'משתמשים',
    myActivities: 'הפעילויות שלי',
    personalInfo: 'פרטים אישיים',
    invalidSignIn: "פרטי כניסה שגויים",
    signOut: 'התנתקות'
} 
declare module 'remult' {
    export interface UserInfo {
        bid: string;
    }
}
 
 